#!/usr/bin/env bash
# Install / update the onec-restart webhook service on the 1C VM.
#
# Usage:
#   scripts/install-restart-svc.sh               # install or update
#   scripts/install-restart-svc.sh --uninstall   # remove from VM
#
# Reads VM connection from infra/vm/.env (MGMT_VM_IP) and uses the SSH key
# generated by scripts/hyperv/New-OnecInfraVm.ps1.
#
# On first run, generates a 32-byte token and stores it in both
#   /etc/onec-restart/token            (on the VM, mode 0640, root:sandbox)
#   secrets/onec_restart_token         (in this repo, gitignored)
# so the dev-container wrapper (.devcontainer/bin/restart-1c) can use it.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SSH_KEY="${REPO_ROOT}/.cache/hyperv/_ssh/onec-infra/id_ed25519"
TOKEN_FILE_LOCAL="${REPO_ROOT}/secrets/onec_restart_token"
ENV_FILE="${REPO_ROOT}/infra/vm/.env"
SVC_SRC_DIR="${REPO_ROOT}/infra/vm/restart-svc"

read_env() {
  awk -F= -v k="$1" '
    /^[[:space:]]*#/ {next}
    $1 ~ ("^[[:space:]]*" k "[[:space:]]*$") {
      v=$2; sub(/^[[:space:]]+/,"",v); sub(/[[:space:]]+$/,"",v); gsub(/\r$/,"",v); print v
    }
  ' "$ENV_FILE"
}

[[ -f "$ENV_FILE" ]] || { echo "ERROR: $ENV_FILE not found" >&2; exit 1; }
[[ -f "$SSH_KEY"  ]] || { echo "ERROR: SSH key not found: $SSH_KEY" >&2; exit 1; }

VM_IP="$(read_env MGMT_VM_IP)"
[[ -n "$VM_IP" ]] || { echo "ERROR: MGMT_VM_IP missing from $ENV_FILE" >&2; exit 1; }

SSH_USER="${ONEC_SSH_USER:-sandbox}"
SSH_OPTS=(-o StrictHostKeyChecking=accept-new -o UserKnownHostsFile=/dev/null -o LogLevel=ERROR -i "$SSH_KEY")
SSH_TARGET="${SSH_USER}@${VM_IP}"

remote() { ssh "${SSH_OPTS[@]}" "$SSH_TARGET" "$@"; }
copy()   { scp "${SSH_OPTS[@]}" "$@"; }

if [[ "${1:-}" == "--uninstall" ]]; then
  echo "[onec-restart] uninstalling on $SSH_TARGET"
  remote 'sudo systemctl disable --now onec-restart.service 2>/dev/null || true
          sudo rm -f /etc/systemd/system/onec-restart.service /opt/onec-restart/restart_svc.py
          sudo rmdir /opt/onec-restart 2>/dev/null || true
          sudo rm -rf /etc/onec-restart
          sudo systemctl daemon-reload
          sudo ufw delete allow from 192.168.250.0/24 to any port 8765 proto tcp 2>/dev/null || true'
  echo "[onec-restart] uninstalled"
  exit 0
fi

# 1. Token: reuse local one if present, else generate and save.
if [[ -s "$TOKEN_FILE_LOCAL" ]]; then
  TOKEN="$(tr -d '[:space:]' < "$TOKEN_FILE_LOCAL")"
  echo "[onec-restart] using existing token from $TOKEN_FILE_LOCAL"
else
  TOKEN="$(python3 -c 'import secrets; print(secrets.token_hex(32))')"
  mkdir -p "$(dirname "$TOKEN_FILE_LOCAL")"
  umask 077
  printf '%s\n' "$TOKEN" > "$TOKEN_FILE_LOCAL"
  echo "[onec-restart] new token generated → $TOKEN_FILE_LOCAL"
fi

# 2. Push files to the VM (staging in /tmp, then moved with sudo).
echo "[onec-restart] copying files to $SSH_TARGET"
copy "${SVC_SRC_DIR}/restart_svc.py"        "${SSH_TARGET}:/tmp/restart_svc.py"
copy "${SVC_SRC_DIR}/onec-restart.service"  "${SSH_TARGET}:/tmp/onec-restart.service"

# 3. Install (token piped via stdin to avoid leaking via argv/env).
echo "[onec-restart] installing service on VM"
printf '%s' "$TOKEN" | remote 'sudo usermod -aG docker sandbox
  sudo install -d -m 0755 /opt/onec-restart
  sudo install -m 0755 /tmp/restart_svc.py /opt/onec-restart/restart_svc.py
  sudo install -m 0644 /tmp/onec-restart.service /etc/systemd/system/onec-restart.service
  rm -f /tmp/restart_svc.py /tmp/onec-restart.service
  sudo install -d -m 0750 -o root -g sandbox /etc/onec-restart
  sudo tee /etc/onec-restart/token >/dev/null
  sudo chown root:sandbox /etc/onec-restart/token
  sudo chmod 0640 /etc/onec-restart/token
  sudo ufw allow from 192.168.250.0/24 to any port 8765 proto tcp >/dev/null 2>&1 || true
  sudo systemctl daemon-reload
  sudo systemctl enable --now onec-restart.service
  sudo systemctl restart onec-restart.service
  sleep 1
  sudo systemctl is-active onec-restart.service'

echo "[onec-restart] done. Test from this machine:"
echo "  curl -fsS http://${VM_IP}:8765/health"
echo "  curl -fsS -X POST -H \"Authorization: Bearer \$(cat ${TOKEN_FILE_LOCAL})\" http://${VM_IP}:8765/restart/onec-server"
